ip-address: 172.16.16.16

virtualbox:
    name: 'WISA Stack'
    cpus: 2
    memory: 2048
    gui: false
    usb3: "off"

iis:
    username: ""
    password: ""
    downloadpath: ""

asp:
    asp35: $true
    asp45: $true

sql:
    downloadpath: ""
    instancename: ""
    rootpassword: ""
    #NOTE: Port-number has to be between 49152 and 65535
    tcpportnr: "50000"
    dbname: ""
    username: ""
    password: ""

folders:
    provision: './scripts'
